name: Notify on merged PR
on:
    pull_request:
        types:
            - closed

jobs:
    notify_merged_pr:
        name: Notify on merged PR
        runs-on: ubuntu-24.04
        if: ${{ github.event.pull_request.merged == true }}
        steps:
            - uses: abinoda/slack-action@master
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.VIZZUHQ_SLACK_API }}
              with:
                  args: '{\"channel\":\"${{ secrets.VIZZUHQ_SLACK_CHANNEL }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*REPO:* vizzu-lib\n*PR:* ${{ github.event.pull_request.title }}\n*Description :* ${{ github.event.pull_request.body }}\n*Opened by :* ${{ github.event.pull_request.user.login }}\n*Merged at:* ${{ github.event.pull_request.merged_at }}\n<${{ github.event.pull_request.html_url }}|View PR>\"}}]}'
              if: success()
